### ISSUE TITLE
Bond stiffness

### ISSUE THREAD

**Issue by JackHenry281** [ProkopHapala/ProbeParticleModel#10]
Hi again,

I have also been playing with confining the PP in certain directions. I attempted this by setting the 'stiffness' values to 999.

When Kx is set to 999 and Ky is set to 1.0 the images still look symmetric. This suggests to me the Ky value is always set to the Kx value and can not be independently set.

Admittedly this is not a major issue, but I thought it might be worth flagging :)

**Comment by ondrejkrejci** [comment]
Repaired. Tested. Merged.
By the way the stiffness asymmetry doesn't give you as much asymmetric image as you would expect.
Cheers,
Ondrej
