### ISSUE TITLE
Wrong sign for Pauli force in density-overlap model

### ISSUE THREAD

**Issue by NikoOinonen** [ProkopHapala/ProbeParticleModel#112]
I looked into this again after getting back to trying to complete #35, and I'm pretty sure the sign for the Pauli force is wrong in the pyridine density overlap example.

If I run the example and look at the vdW and Pauli forces in the z direction, they both have the same sign, they are both attractive.

vdW:
<img src="https://user-images.githubusercontent.com/42408893/225885509-8c2801f9-c55b-4842-92ff-016e2a983287.png" alt="image" width="400"/>

Pauli:
<img src="https://user-images.githubusercontent.com/42408893/225886336-79f7247c-e148-44d8-ad47-7e2bdbed5bd9.png" alt="image" width="400"/>

And looking at the code, these two contributions are simply summed together with a scaling constant `Apauli` at https://github.com/Probe-Particle/ppafm/blob/74180f913ec13805947bc124f40dd3acd30c0587/ppafm/HighLevel.py#L100 and `Apauli` is just set to `1.0`.

However, the resulting images look reasonable:
<img src="https://user-images.githubusercontent.com/42408893/225889002-5a12a0d5-21dc-45fa-9200-32af8ff39642.png" alt="image" width="400"/>

It seems the reason for this is that the electrostatic force saves it. If I set the charge multiplier to 0: `-q 0.0`, then the images break. There is no sharp lines between the atoms anywhere, because there is no repulsive force:
<img src="https://user-images.githubusercontent.com/42408893/225889261-0228ae32-0050-49d9-b644-a1822e9538bc.png" alt="image" width="400"/>

Clearly the vdW and Pauli should not have the same sign. Normally the Pauli force should be positive, but there was recently some discussion that the sign convention is not really clear, so I'm actually not sure which one should be multiplied by -1.

@ProkopHapala Could you look at this and give me your opinion.

**Comment by ProkopHapala** [comment]
Aha, thanks @NikoOinonen  

> However, the resulting images look reasonable:

yes, exactly, when I was testing it with vdW, I saw this image and I though it is fine. But yes, should plot the curves.

**Comment by NikoOinonen** [comment]
@ProkopHapala I looked into this, and I think I know what the issue is, but it's better if you also give your opinion to make sure it's right. Maybe @ondrejkrejci as well.

I was mentioning this before, but it looks like we don't take into account the fact that the force is defined as the _negative_ gradient of the energy, so I believe that these lines in `potential2forces_mem` should actually have a minus sign in front of them: https://github.com/Probe-Particle/ppafm/blob/fc6a4a54fa6419b5b0535df9942081cb7ffb8f7c/ppafm/fieldFFT.py#L292-L294

However, this function is also used for calculating the electrostatic force, which actually comes out right. I actually think
we make two sign errors there that cancel out:
1.  The negative sign on the gradient.
2. All (or most?) of the DFT codes output the Hartree potential in units of energy (eV) instead of electric potential (V), like it should be in the convolution formula. The energy is the energy that an electron has in that potential, and the charge of the electron is negative, so the potential has the wrong sign.

 If this is correct, then there are two options on what we can do to fix it:
1. Just add an additional multiplication by -1 to `conv_rho.py` before the force is saved to file.
2. Fix both sign errors for the electrostatics calculation, and the Pauli sign is fixed automatically as well.

I would probably do 2. to make the physics more consistent throughout the code.

**Comment by ProkopHapala** [comment]
> I actually think we make two sign errors there that cancel out

That is quite problable. I always make these kind of sign errors, and I only judge if it is right from the results

> If this is correct, then there are two options on what we can do to fix it:
> 1. Just add an additional multiplication by -1 to `conv_rho.py` before the force is saved to file.
> 2. Fix both sign errors for the electrostatics calculation, and the Pauli sign is fixed automatically as well.
> I would probably do 2. to make the physics more consistent throughout the code.

yes, I agree about the second option. So will you tray it?

Personally I would like to see some F(z) curves (for E_el, E_pauli, E_vdW and compare them to Fz_el, Fz_pauli, Fz_vdW ), then I would be sure it is correct.  

this script is supposed to be used for it:
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/cli/utilities/plotZcurves.py

**Comment by NikoOinonen** [comment]
>yes, I agree about the second option. So will you tray it?
>
> Personally I would like to see some F(z) curves (for E_el, E_pauli, E_vdW and compare them to Fz_el, Fz_pauli, Fz_vdW ), then I would be sure it is correct.

I can do this soon.
