### ISSUE TITLE
Merge of version2

### ISSUE THREAD

**Issue by kkosmider** [ProkopHapala/ProbeParticleModel#2]
Hi All,

Since it is not very convenient to live too long with two unsynchronized branches I have finally merge version2 branch to master branch. I did some unnecessary commits, sorry for that.

On the way I have discussed all the issues with ProkopHapala and I hope that yakutovicha will not be confused with the changes.

From now, the version2 branch Is considered as historical.

best
kkosmider

**Comment by yakutovicha** [comment]
Hi, 

I'm not confused :)

I think since the branches are merged now we can remove the version_2, since it's not needed anymore.

Best,
Sasha
