### ISSUE TITLE
VLJ unit 

### ISSUE THREAD

**Issue by Msunshinep** [ProkopHapala/ProbeParticleModel#8]
hello，I want to heave a look on the L-J potential, I save the VLJ  during the calculation. The unit  in the VLJ file is eV ?

**Comment by ProkopHapala** [comment]
yes, eV (depends on chopice of tip particle)

**Comment by Msunshinep** [comment]
Thank you very much, what do you mean for the dependence for the tip particle( I try the dz2 tip now),
you mean it is related to the L-J parameter for the tip particle i used?

**Comment by ProkopHapala** [comment]
yes, that the result does not depend only on sample , but also on choice of tip particle (like CO, Xe).
Let me know if there is something inconsistent or suspicious.

**Comment by Msunshinep** [comment]
Thank you for your detailed reply !
